server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/boards/**
      default-filters:
        - name : GlobalAuthFilter
          args :
            baseMessage: Spring Cloud Gateway Global Filter

  session:
    redis:
      namespace: shboard:session

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
