server:
  port: 9001

spring:
  application:
    name: api-gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888


#  session:
#    redis:
#      namespace: shboard:session
